ssr-web-app-staging_app_e79be42_env_1a87bd7.yaml Updated

diff --git a/.github/workflows/ssr-web-app-staging_app_e79be42_env_1a87bd7.yaml b/.github/workflows/ssr-web-app-staging_app_e79be42_env_1a87bd7.yaml
--- a/.github/workflows/ssr-web-app-staging_app_e79be42_env_1a87bd7.yaml
+++ b/.github/workflows/ssr-web-app-staging_app_e79be42_env_1a87bd7.yaml
@@ -2,8 +2,8 @@ name: ssr-web-app-staging_app_e79be42_env_1a87bd7 Pipeline (Skyu Generated)
 'on':
   push:
     branches:
-      - staging
       - release/*
+      - main
     paths-ignore:
       - .github/workflows/**
       - .trivyignore
@@ -15,7 +15,7 @@ name: ssr-web-app-staging_app_e79be42_env_1a87bd7 Pipeline (Skyu Generated)
 env:
   ENCODED_PIPELINE_SECRET: ${{secrets.NEXTAPP_SSRWEBAPPSTAGING_APP_E79BE42_ENV_1A87BD7}}
   COMMIT_ID: ${{github.event.client_payload.commitId || github.sha || github.run_id}}
-  BRANCH_NAME: ${{github.event.client_payload.branchName || github.ref}}
+  BRANCH_NAME: ${{github.event.client_payload.branchName || github.event.branch}}
   DEPLOY_STEP_SHOULD_DEPLOY: 'false'
 jobs:
   code-scan:
@@ -334,6 +334,52 @@ jobs:
               echo "Starting Amplify Job"
               aws amplify start-job --app-id $appId --branch-name $BRANCH_NAME --job-type RELEASE
               
+  deploy:
+    name: Deploy
+    permissions: write-all
+    runs-on: ubuntu-latest
+    needs:
+      - build-ssr-web-app
+      - _status_testing
+    if: github.event.client_payload.releaseData == null
+    steps:
+      - name: 'Run :: Decoding Secrets'
+        run: |2-
+
+                if [ ! -x "$(command -v jq)" ]; then
+                  echo "jq not found, installing..."
+                  sudo apt-get update
+                  sudo apt-get install -y jq
+                fi
+                echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
+                
+      - name: 'Run :: Deploy and Notify Resource Service'
+        env:
+          RUN_ID: ${{ github.run_id }}
+          SHA: ${{ github.sha }}
+          COMMIT_USER: ${{ github.event.head_commit.author.name }}
+          COMMIT_TIME: ${{ github.event.head_commit.timestamp }}
+          COMMIT_MESSAGE: >-
+            ${{ github.event.head_commit.message ||
+            github.event.client_payload.commitMessage }}
+        run: |2-
+              
+              response=$(curl -X PATCH -d "imageRegistryURL=${{ env.IMAGE_NAME }}&appVersionId=${{ env.DEPLOYMENT_APP_VERSION_ID }}&tag=${{ env.COMMIT_ID }}&containerName=${{ env.DEPLOYMENT_CONTAINER_NAME }}&shouldDeploy=${{env.DEPLOY_STEP_SHOULD_DEPLOY}}&pipelineRunId=$RUN_ID&commitDetails[commitHash]=$SHA&commitDetails[commitAvatar]=https://github.com/$COMMIT_USER.png&commitDetails[commitTime]=$COMMIT_TIME&commitDetails[commitMessage]=$COMMIT_MESSAGE&commitDetails[commitUser]=$COMMIT_USER"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-application-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded'  "${{ env.DEPLOYMENT_ENDPOINT }}")
+              
+              status_code=$?
+
+              if [ $status_code -eq 0 ]; then
+                if echo "$response" | grep -q '"success":true'; then
+                  echo "SUCCESS :: $response"
+                else
+                  echo "FAILED :: $response"
+                  exit 1
+                fi
+              else
+                echo "Failed to deploy. HTTP status code: $status_code"
+                exit 1
+              fi
+            
   _status-success:
     name: ' Status Success'
     permissions: write-all
@@ -394,48 +440,3 @@ jobs:
               context=$(echo "$CONTEXT_JSON" | jq -c . | base64)
               response=$(curl -X PUT -d "runId=$RUN_ID&context=$context"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded'  "${{ env.PIPELINE_SERVICE_EP }}/${{ env.PIPELINE_ID }}/FAILED?releaseId=${{ github.event.client_payload.releaseData.releaseId }}")
               
-  deploy:
-    name: Deploy
-    permissions: write-all
-    runs-on: ubuntu-latest
-    needs:
-      - build-ssr-web-app
-    if: github.event.client_payload.releaseData == null
-    steps:
-      - name: 'Run :: Decoding Secrets'
-        run: |2-
-
-                if [ ! -x "$(command -v jq)" ]; then
-                  echo "jq not found, installing..."
-                  sudo apt-get update
-                  sudo apt-get install -y jq
-                fi
-                echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
-                
-      - name: 'Run :: Deploy and Notify Resource Service'
-        env:
-          RUN_ID: ${{ github.run_id }}
-          SHA: ${{ github.sha }}
-          COMMIT_USER: ${{ github.event.head_commit.author.name }}
-          COMMIT_TIME: ${{ github.event.head_commit.timestamp }}
-          COMMIT_MESSAGE: >-
-            ${{ github.event.head_commit.message ||
-            github.event.client_payload.commitMessage }}
-        run: |2-
-              
-              response=$(curl -X PATCH -d "imageRegistryURL=${{ env.IMAGE_NAME }}&appVersionId=${{ env.DEPLOYMENT_APP_VERSION_ID }}&tag=${{ env.COMMIT_ID }}&containerName=${{ env.DEPLOYMENT_CONTAINER_NAME }}&shouldDeploy=${{env.DEPLOY_STEP_SHOULD_DEPLOY}}&pipelineRunId=$RUN_ID&commitDetails[commitHash]=$SHA&commitDetails[commitAvatar]=https://github.com/$COMMIT_USER.png&commitDetails[commitTime]=$COMMIT_TIME&commitDetails[commitMessage]=$COMMIT_MESSAGE&commitDetails[commitUser]=$COMMIT_USER"  -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-environment-id: ${{ env.PIPELINE_ENVIRONMENT_ID }}' -H 'x-application-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded'  "${{ env.DEPLOYMENT_ENDPOINT }}")
-              
-              status_code=$?
-
-              if [ $status_code -eq 0 ]; then
-                if echo "$response" | grep -q '"success":true'; then
-                  echo "SUCCESS :: $response"
-                else
-                  echo "FAILED :: $response"
-                  exit 1
-                fi
-              else
-                echo "Failed to deploy. HTTP status code: $status_code"
-                exit 1
-              fi
-            
